### PR TITLE
Add Cortex-M33 support, fix patches

### LINKED ISSUE #4: Patches fail to apply but pipeline suceeds
The patches in the automatic update pipeline fail to apply:
```
error: while searching for:
    #define ipconfigNETWORK_MTU    1500
#endif

#ifndef ipconfigTCP_MSS
    #define ipconfigTCP_MSS    ( ipconfigNETWORK_MTU - ( ipSIZE_OF_IPv4_HEADER + ipSIZE_OF_TCP_HEADER ) )
#endif

error: patch failed: FreeRTOS-Plus-TCP/include/FreeRTOSIPConfigDefaults.h:395
error: FreeRTOS-Plus-TCP/include/FreeRTOSIPConfigDefaults.h: patch does not apply
```

The pipeline succeeds nevertheless. I'll fix the error reporting.

### PR DESCRIPTION
**Pull request by chris-durand**
This adds the files for Cortex-M33 support. Furthermore, the updater fails now if patches do not apply (#4). Some have been failing for some time and nobody noticed.

- [x] Add CM33 port
- [x] Make updater fail if patches do not apply
- [x] Fix patches

### CODE REVIEW

**Comment by chris-durand** [comment]
The update is now aborted with failing patches:
```
Apply patches...
Checking patch FreeRTOS-Plus-TCP/include/FreeRTOSIPConfigDefaults.h...
error: while searching for:
    #define ipconfigNETWORK_MTU    1500
#endif

#ifndef ipconfigTCP_MSS
    #define ipconfigTCP_MSS    ( ipconfigNETWORK_MTU - ( ipSIZE_OF_IPv4_HEADER + ipSIZE_OF_TCP_HEADER ) )
#endif

error: patch failed: FreeRTOS-Plus-TCP/include/FreeRTOSIPConfigDefaults.h:395
error: FreeRTOS-Plus-TCP/include/FreeRTOSIPConfigDefaults.h: patch does not apply
Applying patch 'patches/tcp_config.patch' failed!
```

**Comment by chris-durand** [comment]
I have triggered the updater job to run on this branch and it fails now as it should.

**Comment by chris-durand** [comment]
Freertos is working with STM32L5 / CM33 and this branch (see https://github.com/modm-io/modm/pull/800)

**Review by salkinium — APPROVED** [review]
Thanks! I will merge this together with the modm PR.

**Pull request merged**
